version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: fines-management
    environment:
      POSTGRES_DB: fines-management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
